### ISSUE TITLE
Improve mobile layout of the editor

### ISSUE THREAD

**Issue by RyanRutkin** [plnkr/feedback#103]
So, I know that writting code on a cell phone isn’t ideal, but there have been numerous times that I have wanted to develop code on my phone. Writing code is basically what I do to pass the time.

Please, PLEASE make the new Plunker mobile responsive!

I have 7+ years experience as a full-stack JavaScript. I know that this isn’t too much to ask for...

If you would like help writing the new UI for Plunker, let me know. I would be happy to contribute.

P.S. I’m surprised that there isn’t a Plunker mobile app...

**Comment by ggoodman** [comment]
> I have 7+ years experience as a full-stack JavaScript. I know that this isn’t too much to ask for...

This is a side project. I'm doing my best.

> If you would like help writing the new UI for Plunker, let me know. I would be happy to contribute.

Thanks for the offer, I will take that into consideration.

> P.S. I’m surprised that there isn’t a Plunker mobile app...

Again, this is a side project by a single person. There are only so many hours in a day.
