### ISSUE TITLE
Where is the RUN button for new JS file?

### ISSUE THREAD

**Issue by rr20eid10** [plnkr/feedback#107]
I used the boilerplate JS file you provide when I created a new js project to test a simple RxJS project.   I want to log some simple feedback in the console, but I can't find the **RUN** button?  It's in the old version, where is it in the new version?

New:
![image](https://user-images.githubusercontent.com/6556523/42175256-d51a6ab4-7df2-11e8-947b-e3f13c4135c0.png) 
Old:
![image](https://user-images.githubusercontent.com/6556523/42175031-2c37a27c-7df2-11e8-80cb-2864cd9c3422.png)

**Comment by ggoodman** [comment]
Please see the `Preview` button in the top right. When you re-open a saved plunk or start a new project, the preview pane should also show up in a 'deferred' mode.

**Comment by rr20eid10** [comment]
@ggoodman  Thanks!
