### ISSUE TITLE
Tag link issue

### ISSUE THREAD

**Issue by stewx** [plnkr/feedback#109]
Go here and click "angular" on the left. It will take you to the same page and the more you click it, the longer the URL gets, with repetitive parameters.

https://next.plnkr.co/collections/plunker/public?tags=angular

It becomes:
https://next.plnkr.co/collections/plunker/public?tags=angular&tags=angular&tags=angular&tags=angular&tags=angular

**Comment by ggoodman** [comment]
Nice catch @stewx.

Beyond that issue, what do you think about the search functionality?

**Comment by stewx** [comment]
I couldn't see a way to sort by popularity, which would be nice
