### ISSUE TITLE
related angular problem

### ISSUE THREAD

**Issue by Aman290** [plnkr/feedback#111]
I think in plunker angular 2 to  angular 5 files not working.Check it http://next.plnkr.co/edit/KVuXxDp0qinGDyo307QW?p=preview&utm_source=legacy&utm_medium=banner&utm_campaign=next&preview

**Comment by ggoodman** [comment]
Hello @Aman290, this looks like a Plunk that relies on static assets hosted on `code.angularjs.org` that are no longer hosted there. This tells me that this is a bug with the Plunk's code and not with the platform itself.
