### ISSUE TITLE
It is not loading all my plunks. There is missing pagination. 

### ISSUE THREAD

**Issue by Striz** [plnkr/feedback#116]
Hi Geoff,

I 
I can view just 9 plunks.
It doesnt load rest of my pluks.
Page numbering is missing. 
Pagination.
Can you help me,please? 

Thanx

**Comment by ggoodman** [comment]
Hi @Striz,

The pagination links are at the bottom of [the account page](https://next.plnkr.co/account/plunks). Are these not being shown for you?

**Comment by Striz** [comment]
Page numbers links dont show up.
So i cant go to 2nd page.

**Comment by Striz** [comment]
This is My Plunks page.
Bottom of the page is empty.
![screen shot 2018-07-09 at 17 28 14](https://user-images.githubusercontent.com/18292480/42463270-893ef514-839d-11e8-9550-cf6bd7cca799.png)

**Comment by ggoodman** [comment]
Hello @Striz, you are looking at the legacy Plunker. The feedback in this repository is for the [https://next.plnkr.co](Plunker alpha).

Please try the link I shared here: https://github.com/plnkr/feedback/issues/116#issuecomment-403472628.
