### ISSUE TITLE
NOT WORKING!!!!!!!!!

### ISSUE THREAD

**Issue by RohitBhadra** [plnkr/feedback#134]

**Comment by Maulik009** [comment]
Not working on Chrome...!!!

**Comment by ggoodman** [comment]
What isn't working? I can't fix what I can't know about.

**Comment by Maulik009** [comment]
Just open any demo of plunker on chrome. It's not opening itself.

**Comment by ggoodman** [comment]
I have opened a random Plunk in legacy Plunker and in Plunker alpha.
Neither produced unexpected behaviour. You will need to provide actionable
details.

**Comment by Maulik009** [comment]
I have opened on Ubuntu Chrome v.56.0.4. None of the plunker demo is opened.
