### ISSUE TITLE
plunker never works for me, I search for stackblitz, always working examples.

### ISSUE THREAD

**Issue by edokkir** [plnkr/feedback#144]

**Comment by ggoodman** [comment]
How do you think that this sort of comment is supposed to help? This:

1. Gives zero reports of what is not working
2. Discourages me (someone who has been providing this free service for 6+ years now) from my work
3. Provides no value in helping me identity what could work better

**Comment by edokkir** [comment]
Hi Geoff,

Lets say it wasnt my day and didnt realize I was opening an issue.
You are right, as a coder myself this is not the way to approach a problem,
doesnt help at all, must be proactive, sorry.

Best regards,
Eyup


Geoff Goodman <notifications@github.com>, 20 Tem 2018 Cum, 15:56 tarihinde
şunu yazdı:

**Comment by ggoodman** [comment]
Hope your day turns around, thanks for getting back.
