### ISSUE TITLE
if it isn't broke, don't fix it

### ISSUE THREAD

**Issue by thedaddyrae** [plnkr/feedback#18]
the site now feels like it has gone backwards. ease of use has gone, the original site was far superior to what it is now for some reason, sing chrome the old site doesn't appear as it was so i'm forced to use the new version. The layout needs to be similar to the last, running a plunk is not as easy to find and load as it was. feel frustrated as it had to be by far the best tool for dev work which is accessible anywhere.

**Comment by ggoodman** [comment]
@thedaddyrae I'm really sorry to hear that.

I'm quite confident that this will be a better, and more frictionless solution than the old plunker once we get through this period of feedback.

Can you give me some details on where you are feeling new friction?

Did you know that you can use `Cmd-Shift-Enter` (or `Ctrl-Shift-Enter` on windows / linux) to toggle the preview pane and `Cmd-Enter` (`Ctrl-Enter` on windows / linux) to trigger a manual refresh?

If you're having a tough time figuring out how to delete files, I will be trying to improve the UX, but for now, just try right-clicking a file.

**Comment by thedaddyrae** [comment]
Hi Geoff,

Thanks for the reply, i'm sure i can work with it, i felt some frustration as it was a new layout and couldn't figure it out and wanted to get to it. i didn't know about the short-cut so will make use of that. 
What was the reason for the update if you don't mind me asking
