### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by acmieremet** [plnkr/feedback#20]
if i login i get the sign-up page

**Comment by ggoodman** [comment]
@acmieremet can you walk me through the steps you took and the behaviour you saw?

**Comment by digitalje** [comment]
I am experiencing a similar issue. If I select GitHub as my login, it takes me to the signup page and then attempts to sign me up, which fails saying that my userid already exists.

**Comment by ggoodman** [comment]
I'll check this out.

**Comment by ggoodman** [comment]
@digitalje can you see if this is still a problem for you?
