### ISSUE TITLE
Does not Open in IE 11

### ISSUE THREAD

**Issue by elliot-j** [plnkr/feedback#210]
Accessing https://next.plnkr.co/ in IE 11 on Windows 10 does not load and the console reports several errors (see screenshot). This results in forever getting stuck in a load circle. Attempting navigate to https://plnkr.co/ always results in a redirect to https://next.plnkr.co/ making the existing version of the site not reachable

![plnkr-alpha-errors](https://user-images.githubusercontent.com/17621302/44540320-4d40fd00-a6bb-11e8-8e24-bd4c8f00c22c.png)

System Configuration:
IE 11 on Windows 10 with compatbility mode set to 11/edge
Windows 10 Enterprise 2016 LTSB Version 1607
OS Build 14393.2368

**Comment by BernieSumption** [comment]
Was about to post the same issue.

FYI there's a workaround if you need to debug a plunk in IE11. Open the plunk in another browser, click the blue icon in the top right of the run window to run it in windowed mode, then copy the URL of the run window (http://run.plnkr.co/xxxxxxxx/) and paste that into IE11.

**Comment by ggoodman** [comment]
@elliot-j sorry about that. I'm afraid that I don't have access to an IE11 test environment. 

I've ensured that `"ie >= 11"` is in my babel settings and 'should' have the polyfills set up for each entrypoint. Can you give this a spin again?

**Comment by elliot-j** [comment]
@ggoodman  

`https://plunkr.co/` is now loading and the editor is able to run several of the pre-built templates. Specifically tested the AngularJS 1.5.x and AngularJS + TypeScript templates. However there is a timer/interval/$watch going on in the background  logging an error to the console repeatedly (see Screenshot 1)

Also not sure if this is intended, but `https://next.plunkr.co` is also not working in IE 11. When the URL is opened I am getting an 'open debugger' prompt since I have visual studio installed, and some button on the `New` button does nothing. Do you want me to open a separate issue for `https://next.plunkr.co` ? 


## Screenshot 1 - Repeated Error logs
![image](https://user-images.githubusercontent.com/17621302/66496153-4f0c8200-ea6f-11e9-9780-e0de29afc794.png)

## Screenshot 2 - Launch debugger when next.plunkr is loaded
![image](https://user-images.githubusercontent.com/17621302/66496843-626c1d00-ea70-11e9-8121-5fbfc83cc247.png)
 

## Screenshot 3 next.plukr.co not working logs
![image](https://user-images.githubusercontent.com/17621302/66496870-70ba3900-ea70-11e9-9a96-7e2ef190d572.png)

**Comment by ggoodman** [comment]
I can't make any sense of this via screenshots but I see that Microsoft has free VM images for testing w/ IE11 so I'll give that a spin.

**Comment by elliot-j** [comment]
Just realized i forgot to include my IE patch version details on the original post. Here they are in the event it you need it

![image](https://user-images.githubusercontent.com/17621302/66504106-4fac1500-ea7d-11e9-9ca9-a11de6c9523a.png)

**Comment by ggoodman** [comment]
I've narrowed down the root cause for this and am working with a vendor to get this issue resolved.

**Comment by BernieSumption** [comment]
We (ag-Grid) ask our customers reporting bugs to use Plunker to create a minimal reproduction, which we then confirm and investigate. We support IE11, and if the bug relates to IE11 then we need to view the plunk in IE11.

While it would be ideal if all of Plunker worked in IE11, for our use case it's sufficient simply to be able to run an existing plunk in IE11, which we can do by copying the `run.plnkr.co` link. We can do this currently by copying the run link from a browser that works and pasting it into IE11.

Optional bonus: under the "Plunker is loading" sign you could put a link to the run.plnkr.co page, so that if people go to plunker in an unsupported browser (in which case the editor will never initialise and the loading message stays up forever) at least they can view the saved plunk.

Bernie     :o)

**Comment by ggoodman** [comment]
I've deployed a version of Plunker.next that appears to be working on https://next.plnkr.co but you will see that there are some visual regressions. Hopefully this won't prevent you from getting some mileage out of the platform.

**Comment by elliot-j** [comment]
Thanks @ggoodman  I'm not seeing any of the issues and can make plunks successfully 

As for intended use case, we use plunkr for prototyping and verifying issues reported by customers for internal use enterprise apps in the products we sell. But sadly a great many of our clients (hospitals and medical labs) still rely on IE 11 due to compatibility with other legacy apps they use for various medical workflows. Thankfully this is changing somewhat quickly (for enterprises anyway) due in part to ransomware outbreaks over the last several months and we are expecting to longer support IE 11 sometime around 2022.
