### ISSUE TITLE
error on login with Google or Github

### ISSUE THREAD

**Issue by alireza19330** [plnkr/feedback#247]
the error: 
Cannot read property 'constructor' of undefined

**Comment by RCVarley** [comment]
Same

![image](https://user-images.githubusercontent.com/20630026/45830925-06641880-bcf6-11e8-8c6e-a293d60ad233.png)

**Comment by skgyan** [comment]
same

**Comment by 1jerry** [comment]
Also from next.plnkr.co:
Different error: An internal server error occurred
console:

> Unhandled promise rejection Error: "An internal server error occurred"
> t https://cdn.plnkr.co/build/v1.0.0-99-gb30a6ed/www.37982e907093fc09a943.js:1:38970
> r https://cdn.plnkr.co/build/v1.0.0-99-gb30a6ed/be7fea6c00403e111b36.js:42:139703

before that, I *was* able to sign up using Github, but then it showed "Login window closed." in the orange notification box, including any time I tried to log in after that.

I *was* able to log in at the original version (plnkr.co), but as soon as I clicked on "Editor" to edit something, I got the "Sign in with Github" button as if I were not signed in, which I wasn't again, since I had no plunks.

same with newest FireFox, Chrome and Edge (Windows)

**Comment by TURBOmon** [comment]
Same, Chrome, tried Github, Google, Facebook

"Cannot read property 'constructor' of undefined"

**Comment by MaxiAringoli** [comment]
Same!

**Comment by ggoodman** [comment]
@alireza19330, @skgyan, @1jerry, @TURBOmon, @MaxiAringoli I've made some changes in hopes of addressing this issue.

Can you please open dev tools, try logging in / signing up again and let me know:

1. Is the error still occurring?
2. What do you see in the console?
3. Do you see any http requests returning with 4xx or 5xx status codes? If so, can you share some details about these?

**Comment by 1jerry** [comment]
Still fails with useless message "Login window closed." in newest FireFox.

Almost the same log message.  Your build version in CDN shows 107 instead of 99 and the reported error is no longer "An internal server error":
Unhandled promise rejection Error: "Login window closed."
	o https://cdn.plnkr.co/build/v1.0.0-107-ga6a508e/www.34d54c132fc60556e2c1.js:1:40930
	r https://cdn.plnkr.co/build/v1.0.0-107-ga6a508e/20094c920cd1aa9b2d7a.js:42:139703

**Comment by ggoodman** [comment]
Thanks for checking @1jerry. Back down the rabbit hole for me.

**Comment by ggoodman** [comment]
Hello @1jerry I've found that the data validation for social profiles was too strict and certain users might have legitimate profile fields that were being rejected. I've updated the service and would really appreciate hearing back if this fixes your issue.

**Comment by ggoodman** [comment]
Thanks for your patience and help @1jerry.
