### ISSUE TITLE
Previews fail to fetch new files after a few seconds (status code `500`)

### ISSUE THREAD

**Issue by boghyon** [plnkr/feedback#261]
Issue description: https://github.com/filearts/plunker/issues/153

**Comment by boghyon** [comment]
@ggoodman Would it be possible to tackle this issue? It's unfortunately still reproducible.

**OK:**
- https://run.plnkr.co/plunks/F3t6gI8TPUZwCOnA/ ✔

**FAIL:**
- https://embed.plnkr.co/F3t6gI8TPUZwCOnA?show=preview ❌
- https://plnkr.co/edit/F3t6gI8TPUZwCOnA ❌  
  <sup>(Formerly https://next.plnkr.co/edit/F3t6gI8TPUZwCOnA)</sup>

### Steps to reproduce the issue

1. Open the sample. Start the preview if it's not already running.
2. Wait for about a minute.
3. Either click on ![Plnkr icon - Open the preview in a separate window](https://user-images.githubusercontent.com/12143247/123002321-1a12a100-d3b2-11eb-94b8-f9c27b7a14a5.png) to open the preview in a new separate window  
  or click on one of the list items from the preview (E.g. "Lufthansa") to fetch new resources.

The server responds with a 500 error code.

___

Additionally, **if** the preview disconnects after too long inactivity, it would be nice if the user could be somehow informed by the Plunker UI that the preview needs to be reloaded. The user should be then no longer able to interact with the preview.

**Comment by boghyon** [comment]
Hi @ggoodman,

The internal server error (`500`) is unfortunately still reproducible. Is it possible to tackle this issue soon? As you can see there are multiple issues created due to the server error.

**Comment by ggoodman** [comment]
@boghyon yesterday, I made a significant increase to the TTL of ephemeral previews. Can you see if that has made enough of a difference on this use-case?

**Comment by boghyon** [comment]
Works great. Thank you so much for increasing the TTL!
