### ISSUE TITLE
Plunker not loading anymore

### ISSUE THREAD

**Issue by merlosy** [plnkr/feedback#29]
I'm seeing the new website in alpha version. I logged in with my github account.
I cannot load any of my plunks : "Plunker is loading" forever
I cannot go back to previous version of the site.
I don't want to be mean, but this is very annoying...

**Comment by ggoodman** [comment]
Hey @merlosy, that does sound very frustrating.

You should be able to get the old Plunker by closing and reopening the browser tab until I fix the version switcher.

**Comment by merlosy** [comment]
Actually, I found a working URL from my browser history:
http://plnkr.co/edit/VGCSprNVT1pobOxjWwmT?p=preview

but the one (not working) given by the website is:
https://plnkr.co/plunks/VGCSprNVT1pobOxjWwmT

Refreshing/clearing cache is not solving much.

**Comment by ggoodman** [comment]
@merlosy I've deployed a fix to the version switcher so that now it should be possible to flip back to the legacy plunker.

As for infinite loading, can you tell me if / what you're seeing in the browser's DevTools console?

**Comment by ggoodman** [comment]
It also looks like your plunk is fixed. Did you fix it yourself or have I fixed it through some backend tweaks?

**Comment by merlosy** [comment]
Much better! :)
I used to have "unexpected end on input" in the console about a js bundle.
Didn't touch my plunk though but it seems to be fixed, probably your fix did the job

Thanks!
