### ISSUE TITLE
Download project

### ISSUE THREAD

**Issue by farnoosh84** [plnkr/feedback#320]
Would be great to be able to download your project files as a folder.

**Comment by ggoodman** [comment]
@farnoosh84 you can download your project (or parts thereof) by right-clicking in the file tree:
![image](https://user-images.githubusercontent.com/50030/48351608-aa17d800-e658-11e8-8d37-a6e3cba87bc9.png)

Alternatively, if you're in chrome, you might be able to simply drag your project to your desktop.

**Comment by farnoosh84** [comment]
That's very helpful. Thanks :)
