### ISSUE TITLE
Can't find "Beautify your code" button

### ISSUE THREAD

**Issue by Aratoum** [plnkr/feedback#35]
Can't find "Beautify your code" button, though new version is pretty good, like it.

**Comment by rr20eid10** [comment]
In the title bar of the editor, the third icon from the right: `</>` "_Format your source code_"  
Is that what you mean?

**Comment by ggoodman** [comment]
@Aratoum, the instructions shared by @rr20eid10 above are correct.

Additionally, you can hit `Cmd-Alt-F` when in a code pane to format the current file.
