### ISSUE TITLE
Don't load my plunks

### ISSUE THREAD

**Issue by guillermoguerrero1226** [plnkr/feedback#4]
Good look, but my plunks don't load in the new version.
![image](https://user-images.githubusercontent.com/7500946/39052699-7c3136b2-4472-11e8-9250-9c387951afe9.png)

**Comment by ggoodman** [comment]
Hi @guillermoguerrero1226, thanks for taking the time to let me know.

In the top-right of the screen, do you see an avatar and your username (something like below)?

![image](https://user-images.githubusercontent.com/50030/39066755-293dbaac-44a4-11e8-987f-c268f18909c6.png)

Can you also try a couple things for me?

1. Logging out and then back in?
2. If the problem persists after that, can you share the failing requests from the network tab of dev tools?

**Comment by guillermoguerrero1226** [comment]
Hi,

The problem was solved !, i logging out and when i log in again, the plunks
were loaded correctly

Thanks
Geoff

2018-04-20 13:08 GMT-05:00 Geoff Goodman <notifications@github.com>:

**Comment by mrose15** [comment]
Worked for me too! Thanks @ggoodman!

**Comment by ggoodman** [comment]
Probably fixed w/ #6.
