### ISSUE TITLE
Unable to log in using my GitHub account

### ISSUE THREAD

**Issue by SkypLabs** [plnkr/feedback#40]
Hi,

I just tried out the new version of plunker but I was not able to log in using my GitHub account. I got the following error message:

![plnkr_error_github](https://user-images.githubusercontent.com/9932586/39551386-bae1aa92-4e5c-11e8-8ad2-3b506aacad96.png)

Steps to reproduce:

1. Click on "Log in"
2. Click on the GitHub icon
3. Accept the OAuth permission to read my e-mail address from my GitHub account

**Comment by ggoodman** [comment]
I believe that this was due to a configuration issue. I have re-deployed and believe that it is fixed on https://next.plnkr.co. Please let me know if this is not the case for you.

**Comment by SkypLabs** [comment]
It works well now :+1: Thanks!
