### ISSUE TITLE
Unable to sign-in on legacy Plunker after signing in on Alpha

### ISSUE THREAD

**Issue by crembowski** [plnkr/feedback#41]
I can only sign in with my Github on the alpha version. The older version gives me an error undefined message. When I go to click on "New" in the alpha version, it takes me no where. Frustrated.

**Comment by crembowski** [comment]
I have not changed GitHub names at all. 


Sent from Yahoo Mail for iPhone


On Friday, May 4, 2018, 2:19 PM, Geoff Goodman <notifications@github.com> wrote:


@crembowski did you happen to change github accounts or github usernames at all in the last few years?

**Comment by ggoodman** [comment]
@crembowski is this still an issue for you?

**Comment by ggoodman** [comment]
@crembowski since I haven't heard back, I'm going to close this.
