### ISSUE TITLE
Very bad experience

### ISSUE THREAD

**Issue by TameshwarNirmalkar** [plnkr/feedback#43]
the new plunkr is doesn't edited code...

**Comment by TameshwarNirmalkar** [comment]
New Editor doesn't open!!!

**Comment by ggoodman** [comment]
I had some major infrastructure issues with the approach I took to proxying between old and new and had to roll back. I will re-enable the version switcher once those underlying problems are resolved.

**Comment by TameshwarNirmalkar** [comment]
Thanks!!!
