### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by swisse** [plnkr/feedback#436]
I'd like to profusely thank Plunker for making this playground. I can now preview my small projects online and add files to them just like on my computer. 
Again thank you very much!

**Comment by Leedabord** [comment]
I like that the Ctrl-F / Ctrl-H functions (Find, Replace) in the editor gives us a count of total matches found.  Also, the ability to easily view the console.log

**Comment by ggoodman** [comment]
Thanks so much to both of you for the encouragement. More great things to come!
