### ISSUE TITLE
Usability feedback

### ISSUE THREAD

**Issue by sramesh0512** [plnkr/feedback#44]
1. Run has issues and doesn't work most of the times. And is too slow when it works.

2. Having file explorer and plunk properties in same view was much easier and usable

3. Overall look and feel was better in old version. It gave a feel of compactness and had the coders' attention straight into editor views. Now this view scatters the vision with too much white all over, not much contrast and distracting.

4. Code type fonts for the explorer looks mundane, it could remain same as the default fonts (Open Sans, Helvetica Neue, Helvetica,Arial,sans-serif).
![image](https://user-images.githubusercontent.com/23235021/39573353-842c36ea-4ef0-11e8-8385-229d9ccc3cdf.png)

5. Button positioning could have been retained. Run/Stop just above the editor was usable. Now we will have to goto the left top corner every now and then. Also same color for all buttons adds difficulty to access.
![image](https://user-images.githubusercontent.com/23235021/39570403-de1961e2-4ee5-11e8-9cb4-284769c17bb5.png)

6. Font size of button and other elements looks two sizes down.

**Comment by ggoodman** [comment]
I've made a few UX changes that I hope will address some of your (and others') feedback:

1. Move the plunk info from the top of the workspace to the top of the file tree and remove the button in the toolbar to toggle this.

2. Move the preview toggle button to the right-hand side and made its active vs default appears have better contrast.

3. Move operations to edit plunks details and delete the plunk to a dedicated sidebar pane.

This shows me viewing a plunk of mine with no preview pane visible:

![image](https://user-images.githubusercontent.com/50030/40449732-679e7b20-5ea7-11e8-977e-4284ea8cec14.png)

This shows me viewing a plunk of mine with the preview pane active and the plunk details sidebar active:

![image](https://user-images.githubusercontent.com/50030/40449805-a844b658-5ea7-11e8-929f-a9ed107ad517.png)

I've also moved ALL static assets out of the main url to a dedicated cdn.

You can play with this at https://next.plnkr.co

**Comment by ggoodman** [comment]
@sramesh0512 I'm going to close this for now for lack of response. I believe that my changes should have resolved most (if not all) of your issues.
