### ISSUE TITLE
Allow drop?

### ISSUE THREAD

**Issue by JohnInWI** [plnkr/feedback#446]
New version of Plunker does not allow "drop" when dragged elements are placed?

I like the new version, but this is a deal-killer for me. I teach beginners (4th-8th grade) and use a drag-and- drop snippet manager that greatly reduces the pain for beginning coders.  While the built-in "intellisense" is wonderful, we still must rely on the "cheats" provided with my super-simple snippet manager. These are kids who will easily give up when confronted with syntax issues. Giving up is not allowed in my classroom!

Any chance of allowing"drop" in the new version?

**Comment by ggoodman** [comment]
@JohnInWI can you walk me through what you're trying to do and what you're observing?

**Comment by JohnInWI** [comment]
I use a snippet manager (lifted from Code::Blocks) when I teach beginners. It saves _many_ heartaches. In this case, it's a 4-day robotics camp with internet/ websocket connected robots... Plunker turns out to be an excellent way to write web apps that control the bots from mobile devices. Very nice work!

The windows-based Snippet manager allows you to drag and drop snippets from icons in the manager. Being we have just 4  half-days to build and program robots, the drag-and-drop snippets work well, while at the same time exposing students to actual code. Most windows apps/ IDEs allow for "dropping" the dragged object, and *some* web apps also allow, but I do believe you have to explicitly allow, due to security concerns. 

I recorded a quick screen capture [here](https://youtu.be/MpojPwHa0eU) . You can see the snippet manager in the lower left, 1st successfully dragging short snippets into old Plunker, then unsuccessfully dragging into alpha Plunker.

My 1st Plunker-controlled robotics camp is next week @ a University near Milwaukee, WI. Gonna use "old" Plunker.  Should be interesting...

**Comment by ggoodman** [comment]
@JohnInWI, that was very helpful. Thanks for the feedback.

**Comment by ggoodman** [comment]
I think I might have just fixed your problem. Please refresh.

**Comment by ggoodman** [comment]
I'm going to close because I believe that this should now be fixed. Please don't hesitate to ping me if I'm mistaken.

**Comment by JohnInWI** [comment]
Thanks for the fix. It *mostly* works, when I drag one of the snippets in, there is a red cursor that appears where the drop will occur. The reason I say mostly works, is that the red cursor is 2 or 3 lines below where the actual mouse position is.

Is there a way to get the mouse pointer and the drop spot to line up?

Thanks for all your help!

**Comment by ggoodman** [comment]
Yikes, that's pretty wacky. I've seen that there is a known issue in the Editor component I'm using about figuring out cursor position on wrapped lines. You might want to try turning off line wrapping when using that.

**Comment by JohnInWI** [comment]
That's it! Turn off the wrapped lines and all works perfectly.
Thanks!
