### ISSUE TITLE
great update

### ISSUE THREAD

**Issue by martynov-94** [plnkr/feedback#447]
what's exactly great:
- no modal window when you try to close a tab. it was annoying
- very useful autocomplete. especially convenient that it even reads names out of the comments.
- font is bigger, my eyes love it
- when you insert a big chunk of text, it wraps automatically onto the new lines. had to do it manually before.
that's all i use in plunker, but i'm sure there are a lot of other great things too. thank you for your work.

**Comment by ggoodman** [comment]
Closing this but thanks so much for taking the time to say so!
