### ISSUE TITLE
Many Angular 6/7/8 example links are not working

### ISSUE THREAD

**Issue by pavangayakwad** [plnkr/feedback#448]
I have been browsing through many Angular 6 based examples and none managed to run properly. 
For. ex: https://plnkr.co/edit/t4JwdewzXXBrnQRV6QMe?p=preview

**Comment by pavangayakwad** [comment]
![image](https://user-images.githubusercontent.com/1834890/62533762-1d0b5380-b865-11e9-9d08-a103f2b20744.png)

**Comment by ggoodman** [comment]
Duplicate of #61. Please see the potential solution linked there.
