### ISSUE TITLE
Error when running Angular Projects

### ISSUE THREAD

**Issue by profesorjaviersoldado** [plnkr/feedback#452]
Hello,

I want to communicate that when I run a Angular example in plunker the execution fails.

For example, when running this project:
http://next.plnkr.co/edit/2MUcs44WUo2G1cS2JvX4?p=preview&preview

Appears the console error:
(SystemJS) XHR error (404 Not Found) loading http://run.plnkr.co/preview/cjzb7wsrx00092y630q9q0cn0/traceur

Also if I create a new Angular project and run it, like this:

http://next.plnkr.co/edit/H8KQwfbP6anfm7WN?preview

Appears the console error: 
Error: The runtime host returned non-string file contents for 'http://run.plnkr.co/preview/cjzb82204000g3b63bbnxbihl/index.js'

I appreciate you if help me to run the Angular projects using Plunker.

Thank you very much.

**Comment by ggoodman** [comment]
Hrm, this is a tricky one. Thanks for the helpful report.

**Comment by ggoodman** [comment]
I believe that this issue should now be fixed.

**Comment by ggoodman** [comment]
I'm going to close but please let me know if the issue continues to present itself.
