### ISSUE TITLE
Review and a small remark

### ISSUE THREAD

**Issue by Ishi-Inanis** [plnkr/feedback#466]
Today, the first time I used the alpha version of Plunker. I really liked the changes, but I would like to be able to switch the theme of the entire window to a dark one rather than an open file.
Will such an opportunity be realized in the future?

**Comment by ggoodman** [comment]
I would really love to do this but I think other improvements will take precedence.

**Comment by Ishi-Inanis** [comment]
Good. The main thing is that it's in the plans.
