### ISSUE TITLE
Login with GitHub causes 404

### ISSUE THREAD

**Issue by TomSaporito** [plnkr/feedback#47]
Clicking the GitHub logo will bring me to a 404 on the old plnkr.co.

Through this window I can still log in.  But when I close out the window, I receive a notification that I closed the window and I am not logged in in the alpha version of plnkr

**Comment by ggoodman** [comment]
Hello @TomSaporito I believe that this was a configuration issue that is now fixed on https://next.plnkr.co. Please let me know if you continue to have problems.
