### ISSUE TITLE
Deleting plunks

### ISSUE THREAD

**Issue by mjfneto** [plnkr/feedback#470]
Is it possible? If not, why?

**Comment by ggoodman** [comment]
I'm guessing you've discovered that this is the "Project settings" pane that can be opened using the wrench icon on the left. I'm sharing the solution here in case someone else comes looking.

![image](https://user-images.githubusercontent.com/50030/66340198-aa752d80-e912-11e9-8ce7-1b83bc8f6cf2.png)

**Comment by mjfneto** [comment]
Actually, I closed it because I had forgotten to check if someone else (#415) had already made the same question. This was really helpful, thank you @ggoodman .
