### ISSUE TITLE
Nothing ever seems to work

### ISSUE THREAD

**Issue by pgj1978** [plnkr/feedback#481]
These days no angular examples I click on ever seem to work in plunker.  I see though most people have switched to using different services.

**Comment by ggoodman** [comment]
> I see though most people have switched to using different services.

I'm sorry that this has been your experience but this sort of passive-aggressive attack isn't helping anyone. Please contribute actionable / constructive feedback.

**Comment by pgj1978** [comment]
Actually, its not passive aggressive attack.  If that is your response to
everyone that reports there is a problem it is little wonder this has been
an issues for so long.  There are 2 possibilities here.  Every single link
that I have seen on the internet linking to an angular example for the past
sever months on Plnkr just happens to be dud or there is something wrong
with Plnkr.  I'm going to conclude there something change on this service
that has broken all these examples and was simply trying to inform you of
this.  Instead I'm thanked with a snide remark and probably very little or
no investigation into this problem.  I'm quite sure that I cannot have been
the only person to report the problem.  As I highlighted, very few people
do link to Plnkr anymore, there are many more services out there.  Back
when Plnkr worked, I hardly saw any other sites being linked to.

**Comment by pgj1978** [comment]
After simply googling Angular and Plunker I haven't even managed to find one that works.  Here are a few links.  I don't know if maybe it could be just for me that these don't work but since I have been using multiple different computers it seems unlikely.  Anyway, let me know if you still think I'm passive aggressive.   (in fact maybe I am being this time!)

http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview

https://embed.plnkr.co/plunk/9krSKg

https://plnkr.co/edit/KJtulZ?p=preview

https://plnkr.co/edit/ulPZB1OQwkoFpbderRPk?p=preview

**Comment by ggoodman** [comment]
I'm sorry but the author of a popular template that was widely used failed to make that template future-proof. With new releases of rxjs, the template broke. The problem is the systemjs config, not plunker.

Duplicate of #61
