### ISSUE TITLE
Plunker is broken for Angular 2

### ISSUE THREAD

**Issue by santosh-300** [plnkr/feedback#49]
Everytime when I visited to plukr to see a demo everytime is broken for Angular 2 applications/example

**Comment by ggoodman** [comment]
Hello, @santosh-300. I'm really sorry about that. I'm afraid that many examples were created in a way that was not future proof and are now broken with new releases of `rxjs`. Unfortunately, this reflects badly on the service and there is little that can be done by me to fix things.

In https://next.plnkr.co/edit, I've introduced a new way of managing dependencies that is more idiomatic and is similar to what you would do if you were developing on your own machine with tools like npm and webpack.

I hope that this helps you out.
