### ISSUE TITLE
My Plunks

### ISSUE THREAD

**Issue by mrose15** [plnkr/feedback#5]
I can't access my plunks in the new alpha version. I'm sure this is something you're still working on. Just wanted to call it to your attention. UPDATE: I should have looked at the open issues first. This is a duplicate of: https://github.com/plnkr/feedback/issues/4. Feel free to close.

**Comment by ggoodman** [comment]
Hey @mrose15, thanks. All feedback welcome at this point. Can you take a look at the question and suggestions in #4 and respond there?

Closing this one in favour of #4.
