### ISSUE TITLE
Pretty hard to use it on ipad with on-screen keyboard. Codemirror was more comfy.

### ISSUE THREAD

**Issue by ilyagladko** [plnkr/feedback#503]
I’ve just tickled Monaco editor on it’s official page and it handles touch events a bit better than your version. Thought it tries to scroll the whole page with a code field.as it always did but never should.

Also, Happy New Year!

**Comment by ggoodman** [comment]
@ilyagladko thanks for the feedback and wishes. Happy New Year to you too!

While CodeMirror was never used on Plunker, it is possible that the previous ace editor had better iPad support. There are no current plans to change underlying editor components or to support multiple so I'm going to close this and mark as wontfix. :(
