### ISSUE TITLE
What happened to the Old PLNKR? The new one breaks with my code.

### ISSUE THREAD

**Issue by georgeawg** [plnkr/feedback#519]
The Old PLNKR stopped working for me. It now forces me to use the new PLNKR.

Is there a way to get to the old one?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ggoodman** [comment]
Hi @georgeawg , it is too much of a burden to support the legacy interface. There are currently no plans to continue offering it.

Is there something in the legacy interface that you miss in the new one?

**Comment by georgeawg** [comment]
The following does not work for me.

**index.html**
```
<!doctype html>
<html>
  <head>
    <script src="//unpkg.com/angular/angular.js"><script>
    <link rel="stylesheet" href="lib/style.css">
    <script src="lib/script.js"></script>
  </head>

  <body ng-app="app">
    <h1>Hello Plunker!</h1>
    I can add 1+1={{1+1}}<br>
    $rootScope.hello = {{$rootScope.hello}}
  </body>
</html>
```
**script.js**
```
angular.module("app",[])
.run(function($rootScope) {
  $rootScope.hello = "world";
})
```

https://plnkr.co/edit/BuWJCcGBx5YBYaDE

It worked fine in the old PLNKR.

**Comment by ggoodman** [comment]
Hi @georgeawg, it looks like there were two things at play here:

1. There was an incorrectly closed script tag in the head.
2. The `plnkr.runtime` setting in `package.json` was set to `system` but angular was set up to bootstrap synchronously.

I've fixed both of these in this fork: https://plnkr.co/edit/w1Xo4XWjX89gjEeR

The second issue is much more subtle and may be a bit of a challenge for users during the transition. I'm working on options to make the experience more predictable.

Under the hood, the `system` runtime is used in the new plunker to dynamically load npm modules from publicly-available CDNs. The runtime I built to support this ([plnkr/runtime](https://github.com/plnkr/runtime)), however, is fundamentally asynchronous so whatever logic you put in your javascript will only get executed *AFTER* the DOM has fully loaded. This isn't an issue for libraries like React and Angular but is problematic for the default AngularJS bootstrapping method.

If you start from the provided AngularJS template, this issue should already be solved for you: https://plnkr.co/edit/github:plnkr/starters/v1.4.0/templates/angularjs?open=lib%2Fapp.ts&deferRun=1

**Comment by georgeawg** [comment]
The PLNKR in your reply hangs with
```
[Violation] 'setInterval' handler took 57ms
15[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
441c3f11c06ffa2442e5.js:47 [Violation] 'click' handler took 156ms
441c3f11c06ffa2442e5.js:47 [Violation] 'setTimeout' handler took 158ms
441c3f11c06ffa2442e5.js:47 [Violation] 'click' handler took 195ms
[Violation] Forced reflow while executing JavaScript took 37ms
441c3f11c06ffa2442e5.js:47 [Violation] 'setTimeout' handler took 92ms
441c3f11c06ffa2442e5.js:47 [Violation] 'click' handler took 167ms
441c3f11c06ffa2442e5.js:47 [Violation] 'setTimeout' handler took 76ms
441c3f11c06ffa2442e5.js:47 [Violation] 'setTimeout' handler took 205ms
[Violation] Forced reflow while executing JavaScript took 200ms
```

The arrows in the preview spin.

**Comment by georgeawg** [comment]
Setting

**package.json**
```
{}

```

Seems to work.

https://plnkr.co/edit/BuWJCcGBx5YBYaDE?preview
