### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Dwigth** [plnkr/feedback#52]
I'm getting this error every time I want to login with GitHub. 
`Error.captureStackTrace is not a function`

**Comment by ggoodman** [comment]
Oh that's a weird one. I don't know any environments whereby `Error.captureStackTrace` would not be a function. Any other details in the devtools console?

**Comment by ggoodman** [comment]
This should now be resolved. Can you please confirm @Dwigth.

**Comment by Dwigth** [comment]
Sorry, I can confirm! Excellent, now I can log in!
