### ISSUE TITLE
How to download plnkr as zip at "new" default version?

### ISSUE THREAD

**Issue by guest271314** [plnkr/feedback#523]
**Describe the bug**
No clear way to download plunk as zip at "new" version.

Or, is downloading as zip intentionally omitted from "new" plnkr.co?
**To Reproduce**

Navigate new default version of plnkr.co and try to locate "download plunk as zip" or similar language.

**Expected behavior**
A clear and concise way to download the plnkr as zip in like manner as previous default version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: *nix
 - Browser: Chromium
 - Version: 81

**Additional context**
Can a means be provided to use the previous default version of plnkr, that was recently discontinued as an option, instead of the "new" default version?

**Comment by ggoodman** [comment]
Try right clicking a folder in the file tree! You should even be able to drag folders right to your desktop.

Sounds like it could more discoverable.

**Comment by guest271314** [comment]
> Try right clicking a folder in the file tree! You should even be able to drag folders right to your desktop.

Ok.

> Sounds like it could more discoverable.

Yes. How are individuals expected to know or find out that procedure based on the current text in the site; intuition? Even the basic text that you wrote in the first paragraph.

Here, prefer the "old" version of plnkr. Can that option still be made available?
