### ISSUE TITLE
Upload images/other files from computer

### ISSUE THREAD

**Issue by CarlyRaeJepsenStan** [plnkr/feedback#526]
**Is your feature request related to a problem? Please describe.**
I'm building sites with images and would like to be able to upload the images to my Plunker project and link to them without having to upload them to an external image-hosting site. 

**Describe the solution you'd like**
In the "Create New File" dialog, add a button to upload from computer. 

**Describe alternatives you've considered**
I could use a different web development service, but that wouldn't be any fun... 

**Additional context**
<img width="593" alt="Screen Shot 2020-04-22 at 9 15 46 PM" src="https://user-images.githubusercontent.com/44917034/80058572-7e03b600-84de-11ea-97c3-e708d7d8fa01.png">

**Comment by ggoodman** [comment]
Hi @CarlyRaeJepsenStan, that's a great idea to put an upload button there 🤔.

In the meantime, you can try dragging files straight from your desktop to the sidebar's file tree. Note, however, there there is still a known issue w/ saving and restoring binary files (like images).

**Comment by ggoodman** [comment]
I think I've found the issue. Can you please confirm that things work as described?

Here is an example: https://plnkr.co/edit/mKmaJk7irCT0ohCt?preview

**Comment by boghyon** [comment]
@ggoodman

> In the meantime, you can try dragging files straight from your desktop to the sidebar's file tree

This doesn't seem to work anymore. Are there currently other ways to add small binary files (such as thumbnails, icons, etc.) to the file tree?
