### ISSUE TITLE
Code garbling/duplication on formatting

### ISSUE THREAD

**Issue by aaronzshey** [plnkr/feedback#527]
**Describe the bug**
When I click the format button on the plnkr IDE window my code gets messed up and duplicated

**To Reproduce**
*This bug is finicky and seems to fix itself every now and then - this has happened twice on occasion but I did not capture the problematic code.*

**Errors / logs in developer tools**
300+ errors were fired in the console...
<img width="936" alt="Screen Shot 2020-04-27 at 9 02 57 PM" src="https://user-images.githubusercontent.com/44917034/80446011-82f3ab80-88ca-11ea-804f-480008af696f.png">

**Expected behavior**
The code should have been formatted properly, as plnkr had done so for the several hundred other times I've used the button.

**Screenshots**

![new recording](https://user-images.githubusercontent.com/44917034/80446114-c9490a80-88ca-11ea-8b46-2e77665b68c7.gif)

**Desktop (please complete the following information):**
macOS Catalina, Opera 68 

**Additional context**
The code in question is paper.js - perhaps that has something to do with the error?
Here's the plunk: http://plnkr.co/plunk/lgLRZQumAzZxNL0B

**Comment by ggoodman** [comment]
Huge thanks for the screen capture. This is not something I've been able to reproduce but will look out for it in the future.

**Comment by aaronzshey** [comment]
@ggoodman Of course!  Should I be concerned about all the errors in the console?
