### ISSUE TITLE
plnkr 2MA2uLj4c3cCrVY8 deleted?

### ISSUE THREAD

**Issue by guest271314** [plnkr/feedback#528]
**Describe the bug**
https://plnkr.co/edit/2MA2uLj4c3cCrVY8?preview prints Not Found. 

AFAIK did not delete the plnkr here.
**To Reproduce**
Navigate to above URL. 
**Additional context**
Published and linked to the plnkr here https://github.com/web-platform-tests/wpt/pull/22779#issuecomment-613250320

**Comment by ggoodman** [comment]
Hello @guest271314, it indeed looks like this plunk was deleted. I have restored it.
