### ISSUE TITLE
Feature or bug?  Cmd-clicking file paths doesn't open file. 

### ISSUE THREAD

**Issue by aaronzshey** [plnkr/feedback#529]
**Describe the bug**
Actually I don't know if this should be a bug or a feature request, but when I command click on a path to a local file I don't see the file but instead get an error "failed to open "/lib/filename.js"

**To Reproduce**
1. Have a basic script or style tag, like  `<script src="lib/script.js"></script>`
2. Command-click on the "lib/script.js" part
3. Observe yellow error card in the corner

**Errors / logs in developer tools**
No pertinent errors originating from plnkr, just errors from my project files and dependencies.

**Expected behavior**
I expected plnkr to open my project file. 

**Screenshots**
![recording](https://user-images.githubusercontent.com/44917034/80898705-591bf980-8cbb-11ea-8eff-65f020568344.gif)
Sorry about the terrible quality, I compressed the recording before conversion so it would upload faster.

**Desktop (please complete the following information):**
OS: macOS Catalina
Browser: Opera 68.  Also tested with Safari and Chrome, both browsers produced the same result.

**Additional context**
Command clicking on other external links (ie, unpkg, Google Fonts, etc) opened said links in a new tab, as expected.  From this I presume it is not an error with opening links in general.
Also: in the title of this issue there should not be an apostrophe in "paths".  Oh well...

**Comment by ggoodman** [comment]
Interesting, it looks like the inferred path from the html document isn't understanding relative imports.

Thanks for the detailed explanation.
