### ISSUE TITLE
Feed Back for new upgrade

### ISSUE THREAD

**Issue by ahsanayub360** [plnkr/feedback#53]
I am thankful to you for this new upgrade, its looks dope and easy. Using the old version was not satisfying me mentally but this new version is easy to understand and easily usable. I hope that you will make it much better version from before. you have my wishes with you. Stay blessed and keep doing the good work.

**Comment by ggoodman** [comment]
Thank you so much for this feedback @ahsanayub360. This sort of comment really fires me up and helps motivate me to make positive changes to the tool so many of you rely on!

I'm going to close this issue but would be happy to re-open it if you have any issues you've experienced that you'd like to discuss.

**Comment by mohnishmonu** [comment]
I am really happy for this new upgrade, its looks good and easy to use.Keep enhancing with cool features which makes our life easier :+1:
