### ISSUE TITLE
Can Plunker run full-stack/server-side apps?

### ISSUE THREAD

**Issue by aaronzshey** [plnkr/feedback#531]
**Is your feature request related to a problem? Please describe.**
Feature request is not related to a problem.
However, I performed the following steps to try to construct a full-stack app using plnkr:
1. I installed mongo, express, etc using NPM
2. I made a package.json file with a "start" file
3. I made a file with a bunch of initiators, database access, etc.
4. I ran the whole thing and observed nothing happening.

**Describe the solution you'd like**
This is not really a feature request, I'm just curious if Plnkr has this capability.
 
**Describe alternatives you've considered**
I have used other web-hosting services like Glitch

**Additional context**
None

**Comment by ggoodman** [comment]
I've often thought of adding such a feature but know that it is a massive undertaking. It is good to know about the interest so I will keep it in mind.

However, since there is no short-term ambition to ship this, I'm going to close for now.
