### ISSUE TITLE
Can't save a plunk - server error

### ISSUE THREAD

**Issue by v7inge** [plnkr/feedback#533]
![plunk bug](https://user-images.githubusercontent.com/12271654/82412616-a00c3c00-9a7c-11ea-933a-f0cd19e8d333.png)
The problem occurred yesterday and still actual today. As I try to save [plunk](http://plnkr.co/edit/Q5emLKCTeSKyFdgV?preview), I see an error red pane in the bottom right corner:

> Error saving plunk: An internal server error occured.

I use Yandex Browser 20.4.2.201 (Chromium Engine) on Windows.

**Comment by ggoodman** [comment]
@freshnoon are you still seeing this issue? There may have been a temporary hiccup on the api server that was affecting your ability to save.

If you do happen to see this again, can you please share the details of the failing request from the network tab in dev tools?

**Comment by v7inge** [comment]
> @freshnoon are you still seeing this issue? There may have been a temporary hiccup on the api server that was affecting your ability to save.
> 
> If you do happen to see this again, can you please share the details of the failing request from the network tab in dev tools?

{message: "An internal server error occurred", statusCode: 500, error: "Internal Server Error"}
error: "Internal Server Error"
message: "An internal server error occurred"
statusCode: 500

**Comment by ronanzenatti** [comment]
The problem persists even though I saved many times the project, the website shows the error message

**Comment by ronanzenatti** [comment]
The problem persists even though I tried to save the project many times the website shows the error message.

**Comment by ggoodman** [comment]
Investigating #539, I can see that this appears to be a server-side bug for handling empty directories. I'm going to take a look but in the mean-time, if you delete `images`, you should be able to save.

**Comment by ggoodman** [comment]
This has been fixed and deployed! Thanks for reporting @freshnoon, @ronanzenatti and @Laurenivy8.

**Comment by Laurenivy8** [comment]
Well because it didn't save my progress from last night, I had to type it all back in. Before I typed everything back in, it would let me save, but when I added everything it wouldn't. All I added was a picture and some codes on my index.

________________________________

**Comment by ggoodman** [comment]
Sorry to hear that @Laurenivy8 :'(

Perhaps in the recent projects, your browser was able to save some of those changes: 
![image](https://user-images.githubusercontent.com/50030/93606758-7b769100-f996-11ea-8d13-72c99d6da1b0.png)
