### ISSUE TITLE
rxjs/angular resources not loading

### ISSUE THREAD

**Issue by mwisnicki** [plnkr/feedback#538]
Url: https://plnkr.co/edit/1hkODExVEToFQFzc

First failing url: https://run.plnkr.co/preview/ckd14hp6s00093a65yjwgek8w/rxjs-compat
Error 404

Every Angular example I was trying to open was failing like that.

Disabling extensions/switching browser doesn't help.

**Comment by ggoodman** [comment]
Hi @mwisnicki can you take a look at #61 to see if the recommendations there help you out?

**Comment by mwisnicki** [comment]
@ggoodman thanks, I'm not quite sure what's the minimal change required to make it working but the new template works so that's sufficient. It's a bit unfortunate that many existing plunkers embedded in various blog posts will stay broken though :/

**Comment by mwisnicki** [comment]
@ggoodman Actually given how widespread this problem is (tons of angular examples suffer from it) maybe it would be a good idea to add some code to detect the problem and display a warning pointing to solution?

**Comment by ggoodman** [comment]
@mwisnicki do you have any ideas on what kind of experience you might have appreciated?
