### ISSUE TITLE
Put back the line numbers

### ISSUE THREAD

**Issue by Kairos1972** [plnkr/feedback#54]
i am new to programming.  but I really like having line numbers. It helps when people are pointing out things I could do differentlly

**Comment by Leedabord** [comment]
i believe you can see the line numbers by changing the settings ... use the "gear" icon.  Am I right?

**Comment by ggoodman** [comment]
Good call. I'll change the default!

**Comment by ggoodman** [comment]
The default has been reverted and ass @Leedabord suggested, you can toggle this setting locally so I'm going to close this.
