### ISSUE TITLE
I can't delete my account or my plunks

### ISSUE THREAD

**Issue by stefanfrede** [plnkr/feedback#543]
**Describe the bug**

I want to delete my plunks but I can't.
I want to delete my account but I can't.

**To reproduce**

Go to My Plunks and try to delete a plunk.
Go to My Account and try to delete your account.

**Wished outcome**

Please delete my account. Thank you!

**Comment by ggoodman** [comment]
Hello @stefanfrede, I've deleted your account and any associated data from Plunker. Sorry to see you moving on.

> Note: You may continue to appear logged-in on the site if you still have the cookies and didn't previously log out manually.

**Comment by saul-silos** [comment]
How do I delete a particular  plunk? I'm looking and can´t see any option to do that

**Comment by KlausEverWalkingDev** [comment]
@ggoodman I also want to delete my account. Or give me the option to change my present username that I'm deprecating.
