### ISSUE TITLE
Option to share embed URL with URL parameters for preview

### ISSUE THREAD

**Issue by boghyon** [plnkr/feedback#545]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to open the preview pane automatically with additional URL parameters.

For example, I'd like to share https://embed.plnkr.co/16J1TFICxbqETCzaxuZ0/ but with `?sap-ui-xx-componentPreload=off` (and possibly more parameters) for the preview pane.

Something like this:

<pre><code>https://embed.plnkr.co/16J1TFICxbqETCzaxuZ0?show=preview<em>&lt;?param1=foo&amp;param2...></em></code></pre>

... which would then open the preview with the passed parameter:

![plunk-enhancement-request-open-preview-with-url-parameters](https://user-images.githubusercontent.com/12143247/107129156-a28d1b00-68c3-11eb-829e-4294f7e0224d.gif)

Not sure how the exact syntax for the URL should look like.

**Comment by ggoodman** [comment]
That sounds like a great idea. It will be tricky to encode query params in query params in a way that balances usability with functionality 🤔 .

**Comment by boghyon** [comment]
I'm happy if there is at least the _functionality_. 👍 No problem to escape all characters before sharing the URL.

**Comment by ggoodman** [comment]
@boghyon this is getting shipped right now. The format you will need is to use is: `?preview:%3Fsap-ui-xx-componentPreload=off`.

LMK if this works for you.

**Comment by boghyon** [comment]
I just tried https://embed.plnkr.co/16J1TFICxbqETCzaxuZ0?show=preview:%3Fsap-ui-xx-componentPreload%3Doff%26sap-ui-xx-nosync=warn expecting `/?sap-ui-xx-componentPreload=off&sap-ui-xx-nosync=warn` at the end of the preview URL.

Works well! Thank you for the quick update! 👍

**Comment by boghyon** [comment]
@ggoodman Now an error page is shown if the preview has no parameters. E.g. https://embed.plnkr.co/16J1TFICxbqETCzaxuZ0/

![Embed plunk preview without parameters causes undefined](https://user-images.githubusercontent.com/12143247/108631808-08ed6e00-746c-11eb-9e0e-6839e2b68753.gif)

**Comment by ggoodman** [comment]
Shipping a fix as we speak 🤦🏼 .

**Comment by ggoodman** [comment]
Fix now deployed. Thanks for bringing this to my attention @boghyon ❤️ !

**Comment by boghyon** [comment]
Would be nice if this feature could be documented in https://ggoodman.gitbooks.io/plunker/content/embed.html. Or how can I contribute to that page?

**Comment by boghyon** [comment]
@ggoodman Would be nice if this feature could be documented in https://ggoodman.gitbooks.io/plunker/content/embed.html. Or how can I contribute to that page? Or is there any other documentation place for Plunker where people can contribute to?

**Comment by ggoodman** [comment]
@boghyon I really LOVE this idea. I have been working on a project called Nostalgie (https://nostalgie.dev, https://github.com/ggoodman/nostalgie) that would make it very easy to spin up a docs site for this. I'll take a stab at it tonight.
