### ISSUE TITLE
The code Runs itself without "control + Enter"

### ISSUE THREAD

**Issue by dubeyaditya29** [plnkr/feedback#551]
The code gets run automatically without control+Enter. It doesn't wait for me to complete the code.

The issue is faced when trying to give alert messages on different parts of my code and the alert box pops up even before I am making a change.

Expected behavior should be to wait until I press control+Enter to execute 

![image](https://user-images.githubusercontent.com/48158220/120480002-37b0a400-c3cc-11eb-9b8e-f48e987a48b8.png)

**Comment by ggoodman** [comment]
Hi @dubeyaditya29, can you try disabling automatic refresh in the settings panel?
![image](https://user-images.githubusercontent.com/50030/120492540-28a80280-c388-11eb-9877-29c328cb2b1b.png)

**Comment by dubeyaditya29** [comment]
Thanks @ggoodman
