### ISSUE TITLE
username change

### ISSUE THREAD

**Issue by ovoddanon** [plnkr/feedback#558]

**Comment by ggoodman** [comment]
Hi @ovoddanon, seems you might have changed your mind. If you're still looking to change usernames please send me an email at geoff at plnkr.co from the email associated with your account indicating the desired username.

**Comment by ovoddanon** [comment]
Hi, i've changed my mind because i just created another account with the right username.now if anything i would like to delete the plunker account whose username is "well_203_backup"31.10.2021, 01:05, "Geoff Goodman" ***@***.***>:
Hi @ovoddanon, seems you might have changed your mind. If you're still looking to change usernames please send me an email at geoff at plnkr.co from the email associated with your account indicating the desired username.
