### ISSUE TITLE
Blocked Mixed Content

### ISSUE THREAD

**Issue by yusufkayaer** [plnkr/feedback#560]
**Describe the bug**
When I use plunker I get mixed content error and can't see demo in preview section.

**To Reproduce**
1. Go to https://plnkr.co/edit/SLNE6T8pHq4xZf6s?preview
2. Click on preview section.
3. Open developer tools.

**Errors / logs in developer tools**
Mixed Content: The page at 'https://plnkr.co/edit/SLNE6T8pHq4xZf6s?preview' was loaded over HTTPS, but requested an insecure frame 'http://10.2.11.71:15871/cgi-bin/blockpage.cgi?ws-session=1550244146#ckwvq5m5p0006386lqo4oyofl'. This request has been blocked; the content must be served over HTTPS.

**Expected behavior**
Demo should be visible in preview mode.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [Version 96.0.4664.45 (Official Build) (64-bit)]

**Additional context**
---

**Comment by ggoodman** [comment]
Hello @yusufkayaer, the linked Plunk doesn't produce the same result on my computer. Is it possible that you have a browser extension that is interfering or injecting content?

**Comment by yusufkayaer** [comment]
> Hello @yusufkayaer, the linked Plunk doesn't produce the same result on my computer. Is it possible that you have a browser extension that is interfering or injecting content?

Thanks for answer @ggoodman you became a guide :) 
An web security application we are using may be causing it,i'm working on it.
