### ISSUE TITLE
Cannot use Fetch API after 30 seconds

### ISSUE THREAD

**Issue by Egauon** [plnkr/feedback#561]
The Fetch API cannot be used in my Plunker Project 30 seconds after the project preview has started. I can reload the preview and it works fine... again until 30 seconds later. 

Here is a Plunk that describes the issue:

https://plnkr.co/plunk/OIHKMRQHqbzZYYE5

The Second by Second button calls the fetch API every .2 seconds and the 30 Second one delays the fetch API until the 30 second mark. 

I included both to show that it's not a call quantity issue, seemingly purely time based???

On Google Chrome Windows 10

<<<<<<< EDIT >>>>>>>>

Okay okay so apparently it is only an issue in the editor?????

I previewed the Plunk from a public standpoint and it works fine

Maybe that helps narrow the issue?

Also the Fetch API error code is 500 if that helps as well

**Comment by Egauon** [comment]
Okay okay so apparently it is only an issue in the editor?????

I previewed the Plunk from a public standpoint and it works fine

Maybe that helps narrow the issue?

**Comment by ggoodman** [comment]
Hi, what's happening here is that in-editor previews store their data in an ephemeral storage as a cost-saving measure. Perhaps the TTL or size of this storage is out of tune with current usage patterns.

Unlike previews, saved Plunks are backed by durable storage.

**Comment by Egauon** [comment]
> 

So I'm assuming then there's no way to 'fix' it as it's purposeful?

**Comment by ggoodman** [comment]
There is no fix that is available to users but from the platform perspective I'll take a look later tonight to see what can be done.

**Comment by guest271314** [comment]
Works as expected on Chromium 113 on Linux.

**Comment by ggoodman** [comment]
Hello @guest271314, that should indeed be the case. I bumped the TTL this year, as noted in https://github.com/plnkr/feedback/issues/261#issuecomment-1409617626.
