### ISSUE TITLE
Blank screen on Chromium 103

### ISSUE THREAD

**Issue by guest271314** [plnkr/feedback#563]
**Describe the bug**
Blank screen on Chromium 103

**To Reproduce**
1. Go to [plnkr](https://plnkr.co/)
2. Click on any/all buttons; login; new plnkr
3. Scroll down to DevTools

**Errors / logs in developer tools**
```
545b360bc0082009993c.js:60 Error: [$controller:ctrlreg] The controller with the name 'PlunkerLayoutComponentController' is not registered.
https://errors.angularjs.org/1.8.0/$controller/ctrlreg?p0=PlunkerLayoutComponentController
    at 545b360bc0082009993c.js:60:968
    at 545b360bc0082009993c.js:60:59798
    at 545b360bc0082009993c.js:60:50486
    at ae (545b360bc0082009993c.js:60:50575)
    at 545b360bc0082009993c.js:60:44429
    at 545b360bc0082009993c.js:60:43642
    at Object.<anonymous> (545b360bc0082009993c.js:66:134799)
    at 545b360bc0082009993c.js:60:7304
    at Me (545b360bc0082009993c.js:60:56802)
    at ae (545b360bc0082009993c.js:60:51573) '<body ui-view="" data-ng-animate="1">'
```

**Expected behavior**
No errors. Fully functional site.

**Screenshots**
![Screenshot_2022-05-01_06-17-42](https://user-images.githubusercontent.com/4174848/166148417-ff655b6a-2fd1-4c0d-8ffe-2c37ebdd6a77.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium
 - Version: 103
**Additional context**

**Comment by ggoodman** [comment]
@guest271314 did you happen to see if any network requests failed?

**Comment by guest271314** [comment]
Not that I can point to. Chromium dev channel.
![Screenshot_2022-05-02_06-23-43](https://user-images.githubusercontent.com/4174848/166241054-9425da29-c618-4fb1-a325-ca0185d0e269.png)

**Comment by guest271314** [comment]
This is what Chromium says about Dev channel https://www.chromium.org/getting-involved/dev-channel/#how-do-i-choose-which-channel-to-use

> While this build does get tested, it is still subject to bugs, as we want people to see what's new as soon as possible.

Firefox 99 
![Screenshot_2022-05-02_06-33-37](https://user-images.githubusercontent.com/4174848/166242833-7a85013e-1a25-42b4-8db5-5eef59600509.png)

**Comment by guest271314** [comment]
Working now on Developer build 103.0.5049.0.
