### ISSUE TITLE
Melon.js game field size

### ISSUE THREAD

**Issue by ivan-enzhaev** [plnkr/feedback#567]
When you run it: https://plnkr.co/edit/zDDMRlEZeDQVoNiY?preview you see that a game field is small:

![image](https://user-images.githubusercontent.com/3908473/176994477-e8d54c4e-c9dd-4105-81dc-4c1f1bfaa87d.png)

But if you change a code the size will be normal:

![image](https://user-images.githubusercontent.com/3908473/176994501-054f1788-e08c-4944-8a94-46a5270a89b1.png)

And If you will chance the central border the size will be grow up:

![melonjs-field-resize](https://user-images.githubusercontent.com/3908473/176994670-41dc27b7-d7d2-46ec-a258-42eafc5c9568.gif)

**Comment by ggoodman** [comment]
Hello @8Observer8,

It looks like what is happening is that the html page within the preview is not filling the space given to it and `melon.js` is trying to make a square that fits in the available area.

To fix that, check out [this plunk](https://plnkr.co/edit/CgaqF0eREfBBCSPD) where I added following css to make sure the body fills the preview:
```css
    html, body {
        margin: 0;
        padding: 0;
        width: 100vw;
        height: 100vh;
    }
```

**Comment by ivan-enzhaev** [comment]
Thanks a lot!
