### ISSUE TITLE
Built in console, Yay!

### ISSUE THREAD

**Issue by uzorjchibuzor** [plnkr/feedback#57]
I like the fact that a console came with the UI, as that is one of the major reasons I use the editor while testing my code.

The UX feels great too. Thank you.

**Comment by ggoodman** [comment]
@uzorjchibuzor as @leedabord writes here (https://github.com/plnkr/feedback/issues/54#issuecomment-397097629), you can toggle this setting from the settings pane.

I will, however, change the default to have them enabled.

**Comment by ggoodman** [comment]
Really happy to hear that you noticed the console (you're the first to comment on this). It was quite a bit of work to wire the up :D

**Comment by uzorjchibuzor** [comment]
Great job.

**Comment by ggoodman** [comment]
Line numbers is now the default.

**Comment by Leedabord** [comment]
Easy access to the console is great

**Comment by rr20eid10** [comment]
Great addition!  Thanks!

**Comment by ggoodman** [comment]
Thanks for noticing everyone. I'm going to close this in light of the influx of bugs and feature suggestions.

Note that you're all the reason that this will keep getting better!

**Comment by Judgement1995** [comment]
love it, the console
