### ISSUE TITLE
Ali Ashori 

### ISSUE THREAD

**Issue by aliashori75** [plnkr/feedback#570]
**Describe the bug**

**To Reproduce**

**Errors / logs in developer tools**
Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what *you* would want to know to fix the issue! :heart:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by aliashori75** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Errors / logs in developer tools** Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what _you_ would want to know to fix the issue! ❤️
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

**Comment by aliashori75** [comment]
> > **Describe the bug** A clear and concise description of what the bug is.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to '...'
> > 2. Click on '....'
> > 3. Scroll down to '....'
> > 4. See error
> > 
> > **Errors / logs in developer tools** Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what _you_ would want to know to fix the issue! ❤️
> > **Expected behavior** A clear and concise description of what you expected to happen.
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):**
> > 
> > * OS: [e.g. iOS]
> > * Browser [e.g. chrome, safari]
> > * Version [e.g. 22]
> > 
> > **Additional context** Add any other context about the problem here.

**Comment by aliashori75** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Errors / logs in developer tools** Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what _you_ would want to know to fix the issue! ❤️
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

**Comment by ggoodman** [comment]
Hi @aliashori75, not sure what you're trying to communicate here so I'll be closing this.

**Comment by aliashori75** [comment]
> Hi @aliashori75, not sure what you're trying to communicate here so I'll be closing this.

#571
