### ISSUE TITLE
Run button is missing

### ISSUE THREAD

**Issue by RobinHoody** [plnkr/feedback#58]
My code doesn't execute in the alpha editor and there's no run button, I assume this is an auto run setup but it's not clear. I've followed the demo plunkr from telerik's website so it should be running: https://www.telerik.com/kendo-react-ui/wrappers/dateinputs/datetimepicker/

**Comment by zalla2100** [comment]
To the left of your name should be a "preview" button which is equivalent to run in the old version.

**Comment by ggoodman** [comment]
You can also hit `Cmd + Shift + Enter` to toggle the preview pane and then `Cmd + Enter` to trigger a manual refresh (if you have auto refresh disabled).

**Comment by ggoodman** [comment]
Thanks for stepping in @zalla2100!

**Comment by RobinHoody** [comment]
Thanks guys!
