### ISSUE TITLE
[docs] broken link in /about/features

### ISSUE THREAD

**Issue by jacalata** [plnkr/feedback#582]
**Describe the bug**
On the page https://plnkr.co/about/features, in the paragraph "Embeddable editor", there is a sentence with embedded link to gitbooks. This link takes me to a 401 unauthorized page.

- Go to https://plnkr.co/about/features
- scroll down to "Embeddable Editor"
- click on "a bunch of knobs and levers"

> All the power of the editor, in a clean little box with [a bunch of knobs and levers](https://ggoodman.gitbooks.io/plunker/content/embed.html) to best suit your needs.

**Comment by ggoodman** [comment]
@jacalata that's unexpected. I've tried reproducing that locally (including via incognito) and have been able to open the GitBooks link. Is there something running locally for you that might be getting in the way?

**Comment by jacalata** [comment]
That is strange, yesterday it was giving me a (github generated) 401 but today it's fine. I must have picked a bad moment in the cache.
