### ISSUE TITLE
URL parameters get stripped away after pressing the [Proceed] button from the "Phishing Warning" page

### ISSUE THREAD

**Issue by boghyon** [plnkr/feedback#583]
### Steps to reproduce the behavior
1. Open https://run.plnkr.co/plunks/wp6yes/?initial-focus=target1 in a new browser session (E.g. in an incognito window or using a Guest profile)
2. Notice the URL contains a parameter (`initial-focus=target1`).
3. Click on <kbd>Proceed</kbd>

### Expected behavior
The page keeps all URL parameters upon redirecting to the plunk sample.

### Current behavior
Notice how the URL has no parameter anymore after pressing the <kbd>Proceed</kbd> button.

**Comment by ggoodman** [comment]
Hrm, interesting. Thanks for bringing this up!

**Comment by boghyon** [comment]
@ggoodman Thanks for looking into this issue. It would be great if https://github.com/plnkr/feedback/issues/261 could be fixed first.

**Comment by ggoodman** [comment]
Thanks for the easy repro. I've deployed a fix that seems to resolve this.
