### ISSUE TITLE
Don not work

### ISSUE THREAD

**Issue by 1027154** [plnkr/feedback#588]
Не редактируется код через смартфон на android.

**Describe the bug**

**To Reproduce**

**Errors / logs in developer tools**
Please open developer tools and copy/paste (or take a screenshot of) information that you think would help the team diagnose and fix the issue. We're all developers here after all, so think about what *you* would want to know to fix the issue! :heart:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by ggoodman** [comment]
Hello, there is a bug report template for a reason. Please complete the template and attempt to translate to english and I will revisit this if it is indeed a bug.

**Comment by 1027154** [comment]
Hello! Try to edit the code on android yourself and you will understand what I want to say, if you need support on android
