### ISSUE TITLE
PlayCanvas demo not scaling to requested size in Preview

### ISSUE THREAD

**Issue by ivan-enzhaev** [plnkr/feedback#599]
The requested size of canvas is 300x300 but it is bigger in Preview: https://plnkr.co/edit/nEchdgd1UQYDClR1?preview

![image](https://github.com/plnkr/feedback/assets/3908473/d4ff0831-d140-4d49-8df5-c9cfce0f9c8e)

**Comment by ggoodman** [comment]
Hey, if I remember correctly, there's some subtle trickery going on in the preview. It's an iframe nested within another controller iframe. I believe that the nested iframe gets resized to fit the container given that the space allocated to that controlling iframe is unknown _a priori_.

The following code in your plunk is probably responsible:

```js
// Ensure canvas is resized when window changes size
window.addEventListener("resize", () => app.resizeCanvas());
```

**Comment by 8Observer8** [comment]
I commented it out and the issue was fixed. Thank you very much!

```js
// Ensure canvas is resized when window changes size
// window.addEventListener("resize", () => app.resizeCanvas());
```

**Comment by ivan-enzhaev** [comment]
I commented it out and the issue was fixed. Thank you very much!

```js
// Ensure canvas is resized when window changes size
// window.addEventListener("resize", () => app.resizeCanvas());
```
