### ISSUE TITLE
Taking too much time to load the preview

### ISSUE THREAD

**Issue by jithinkmatthew** [plnkr/feedback#61]
Sometimes, it is taking too much time to load the preview

**Comment by ggoodman** [comment]
Hi @jithinkmatthew, are you using one of the new starter templates?

If so, I have a project in the work that will make a dramatic difference here. Have you noticed that once loaded, the templates should have hot module reloading in effect?

**Comment by jithinkmatthew** [comment]
@ggoodman , I am not able to see the preview in **Plunker**. Please refer this link. I am using alpha version of Plunker.

http://next.plnkr.co/edit/HI3h5nkbRwaQ9fj2jihZ?p=preview&utm_source=legacy&utm_medium=banner&utm_campaign=next&preview

**Comment by ggoodman** [comment]
Hi @jithinkmatthew, I'm sorry that this broke. Unfortunately the template on which that plunk is based had a design flaw. It took a `*` dependency on `rxjs`. As new versions have been released, the SystemJS configuration is inadequate to run the code.

Can you try using the provided Angular template from the alpha at https://next.plnkr.co/edit?

**Comment by jithinkmatthew** [comment]
Thanks for the info...

**Comment by ggoodman** [comment]
Please see https://stackoverflow.com/a/51288714/3753599 for a potential solution.
