### ISSUE TITLE
Unable login https://plnkr.co/

### ISSUE THREAD

**Issue by doggy8088** [plnkr/feedback#618]
**Describe the bug**

No matter what I tried. I can't login into the site:

![image](https://github.com/plnkr/feedback/assets/88981/622684d1-499b-4b69-85db-05fd7dff69a1)

**To Reproduce**
1. Go to [plnkr.co](https://plnkr.co/)
2. Click on 'Log in'
3. Click on 'Google', then a new window popup
4. Login into Google account, then the popup window closed.
5. The page shown below:

    ![image](https://github.com/plnkr/feedback/assets/88981/622684d1-499b-4b69-85db-05fd7dff69a1)

**Comment by ggoodman** [comment]
I wonder if you could share details about anything unusual in dev tools console logs. I'm not personally experiencing this issue.

Can you also share OS and Browder (+ version) please?

**Comment by doggy8088** [comment]
![image](https://github.com/plnkr/feedback/assets/88981/9c5f12f7-8dec-438c-aab9-7ce1484f893a)

OS: `Microsoft Windows [Version 10.0.19045.4412]`

Browser: `Chrome version 125.0.6422.61 (64 bits)`

**Comment by doggy8088** [comment]
@ggoodman I still can't sign in. Do you know why?

**Comment by ggoodman** [comment]
I'm still at a loss. Do you have any other identities among those Plunker supports? You don't need to actually log in with any of them, just do the OAuth flow then I can link on the backend.

**Comment by doggy8088** [comment]
I tried Google and GitHub login. All failed. I think it's JS issue. I don't know why window been closed after sign in.

**Comment by ggoodman** [comment]
Do you happen to have access to other browsers that you could try? Trying to see if it's a regression with a specific browser or potentially something to do with your account.

**Comment by doggy8088** [comment]
I tried Edge & Chrome which are both failed.

**Comment by Thaina** [comment]
Using Chrome also failed too

I think we should start by removing any call to `window.close`, or at least wrap it to not throw exception

**Comment by ggoodman** [comment]
Oh, is `window.close()` problematic for some configurations of Chrome users? Putting that in a `try / catch` is certainly worth trying.

**Comment by doggy8088** [comment]
I finally able to login now.

**Comment by Thaina** [comment]
I still cannot login with google

![image](https://github.com/user-attachments/assets/255ddb03-294f-4293-aab7-27b095887819)
