### ISSUE TITLE
Edit loses cursor position

### ISSUE THREAD

**Issue by rellampec** [plnkr/feedback#69]
- _open the preview in a separated window_ fails (server error)

Among feature that would provide added value:

- would be awesome to have the new plunker remembering the **cursor position** in the code when you navigate to other documents and come back to the one you were editing.

- be able to add/remove an edited file to a tabs container, so you use the project viewer to navigate searching for parts of code, but keep as main current files you are working on always visible in the tabs view above. That way, you easily navigate to find / analyse by using the project viewer (with the folders and files), but can switch quickly to the file you were editing by pressing one of those tabs.

- one last thing that could make a difference is to be able to navigate between functions... with a nested displayer... that would accelerate the way you review code, when going up and down to read the code

**Comment by ggoodman** [comment]
> open the preview in a separated window fails (server error)

Thanks for reporting. This is something that will take a bit more time to address.

>would be awesome to have the new plunker remembering the cursor position in the code when you navigate to other documents and come back to the one you were editing.

I've fixed this. Please let me know if the new behaviour is what you were looking for.

> be able to add/remove an edited file to a tabs container, so you use the project viewer to navigate searching for parts of code, but keep as main current files you are working on always visible in the tabs view above. That way, you easily navigate to find / analyse by using the project viewer (with the folders and files), but can switch quickly to the file you were editing by pressing one of those tabs.

Can you elaborate a bit on this? I love ideas like this to improve the UX but don't quite follow what you're proposing. Did you know that you can drag files from the tree and place them into the workspace so that you can have multiple files visible?

> one last thing that could make a difference is to be able to navigate between functions... with a nested displayer... that would accelerate the way you review code, when going up and down to read the code

Interesting. Do you have any examples on other editors that I could check out?

**Comment by ggoodman** [comment]
I'm going to close this for now because I believe that the core issue has been addressed.

Please file issues for your feature requests if you feel strongly about them
