### ISSUE TITLE
Cannot run default templates

### ISSUE THREAD

**Issue by pynnl** [plnkr/feedback#7]
Currently new plunker does not work for me on any of the default templates. I'm using latest Chrome and Firefox
![image](https://user-images.githubusercontent.com/31667324/39072950-26949aa8-44ba-11e8-99b8-bd5dbb75bd80.png)
![image](https://user-images.githubusercontent.com/31667324/39072974-358a41e8-44ba-11e8-8e13-4c4c6a479d1e.png)

**Comment by ggoodman** [comment]
Yikes that's strange, @pynnl. If you're able to reproduce, can you please share the details of those requests from the network tab of dev tools?

**Comment by pynnl** [comment]
@ggoodman I've just tested again , it's working now, on both Chrome and Firefox, for all default templates. The problem was kinda related to the slow modules  loading, as it would work after spamming the run button in 4-5 mins.

I'm gonna close issue and will report if this happens again. Thank you for your hard work.
