### ISSUE TITLE
Button "No" when deleting a folder, is not working

### ISSUE THREAD

**Issue by jpacareu** [plnkr/feedback#70]
Guys the latest layout looks great, I love it, just the detail that when I try to delete a folder, it shows the popup with **Yes, No** and **X** (close up right) buttons, they all work as expected except the **No** one.

Keep it up 👍

**Comment by ggoodman** [comment]
This should now be fixed.

Closing this issue but if you continue to see issues, let me know.

**Comment by ggoodman** [comment]
Thanks for reporting btw, good catch and helpful description 💯.
