### ISSUE TITLE
Cannot create and account or sign up

### ISSUE THREAD

**Issue by maxx920** [plnkr/feedback#76]
Using the new Plunker. and I tried signing up via the linked account GMAIL but it kept saying the Login in window closed. Or the user name was already used. I even typed in random letters and it would say the name was used.
Same thing goes for when I tried to signup with my GIT account.

**Comment by parkerjgit** [comment]
same problem here

**Comment by ggoodman** [comment]
This is a known issue. Closing in favour of #74
