### ISSUE TITLE
How do you name the plunker?

### ISSUE THREAD

**Issue by rr20eid10** [plnkr/feedback#81]
I may be missing this somewhere in the UI, but where do you name the plunker in the _alpha_ version?

**Comment by ggoodman** [comment]
Check out the 2nd icon along the left side when on a saved plunk. Any ideas how I could make it more discoverable?

**Comment by rr20eid10** [comment]
Ok, thanks, I see in the saved plunk now, you added a wrench icon.  I clicked that to rename my plunk.  Awesome!

>Any ideas how I could make it more discoverable?

In the old version, you could rename it before you saved it using a text input.   Naming it after you save it is a different workflow then the old version.  

IMHO, to keep that experience as painless as possible, you could add the wrench icon and functionality to the toolbox initially.  Or when a user clicks the save button, the user is prompted to name and save the plunk, since most people associate "*Save" with that type of action.  But refactoring the Save functionality may not be what you want to do!

_*Returning users realize that "Save" only saves the plunk and doesn't give you the ability to name it._
