### ISSUE TITLE
login

### ISSUE THREAD

**Issue by waltsully** [plnkr/feedback#9]
I'm unable to use/keep my preferred login name "waltsully" when I linked to GitHub I had to change it to "waltersully" and I'm confused as to why. My email for both accounts is identical

**Comment by ggoodman** [comment]
Hey @waltsully, that sounds like a bug to me.

1. Can you tell me a little bit about how you logged in / signed up?
2. Did you _first_ associate your github account with Plunker fairly recently?
3. On the old Plunker, are you able to login as `waltsully`?

**Comment by waltsully** [comment]
Geoff,

Here’s how I logged in and set-up (best  I can remember)

Friday 6:58pm


Hey waltsully!



A third-party OAuth application (Plunker) with user:email scope was recently authorized to access your account. Visit https://github.com/settings/connections/applications/9d1db857c3215c7cb83a for more information.



To see this and other security events for your account, visit https://github.com/settings/security.



If you run into problems, please contact support by visiting https://github.com/contact.



Thanks,

Your friends at GitHub

Friday 6:49pm



Hey waltsully!



A third-party OAuth application (Plunker) with gist scope was recently authorized to access your account. Visit https://github.com/settings/connections/applications/7e377e5657c4d5c332db for more information.



To see this and other security events for your account, visit https://github.com/settings/security.



If you run into problems, please contact support by visiting https://github.com/contact.



Thanks,

Your friends at GitHub

**Comment by waltsully** [comment]
@ggoodman I just tried "classic" logging in with GitHub and got that red pop-up toast "Undefined" ... while the alpha site logged me in with no issue. 

![image](https://user-images.githubusercontent.com/33215029/39191961-11aef81a-47a6-11e8-9bda-c1759f819350.png)
