### ISSUE TITLE
The width of the edit area NOT adjustable

### ISSUE THREAD

**Issue by amjudson** [plnkr/feedback#90]
It would be nice to be able to adjust to editing width so you wouldn't get line wrapping.

**Comment by ggoodman** [comment]
Hi @amjudson, I think adding a line wrapping width could be a good idea. In the interim, you can enable/disable line wrapping in the settings sidebar (automatically wrap lines):

![image](https://user-images.githubusercontent.com/50030/42120176-d94e220c-7be4-11e8-94e4-740ea65058d3.png)
