### ISSUE TITLE
Version Control - Previous Versions Disappeared?

### ISSUE THREAD

**Issue by dag93tt** [plnkr/feedback#99]
I can't seem to find where all of my previous versions from saves are - the recent projects only shows one or two of my most recent saves from the current session, but not the full list.

It would also be great to be able to label or make comment in the title of each previous version so you can track your progress easily!

**Comment by ggoodman** [comment]
Closing in favour of #79.

> It would also be great to be able to label or make comment in the title of each previous version so you can track your progress easily!

That is a fantastic idea.
